[project]
name = "adventofcode"
version = "0.1.0"
decription = ""
authors = ["Alexandre Morignot <erdnaxeli@cervoi.se>"]
dependencies = [
    "jupyterlab>=4.5.1",
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "trio>=0.32.0",
]
